### PR TITLE
Fix shift guard in decrease

### PR DESCRIPTION
**Pull request by QGarchery**
### Problem
We want to skip `shiftDown` when there are no elements below it in the heap part of the data-structure. 

### Solution

Just check if the first son is in the heap part of the data-structure. This corresponds to `leftMostChildIndex(index) < _heap.size`.

For the 3-heap, this is simply `3 * index + 1 < _heap.size`.

For the 2-heap, this can be checked more efficiently with `index < _heap.size / 2`. This comes from the following general theorem:
$\forall m ~n \in \mathbb{N}. m < \frac{n}{2} \Leftrightarrow 2m + 1 < n$

### Other checks
The following ways to check (for the 3-heap) don't work. 
1. `index < (_heap.size - 1) / 3`
2. `index < _heap.size / 3`

See the added test `testDecreaseGuardLimit` for a counter-example.

### CODE REVIEW

**Review by pakim249CAL — APPROVED** [review]

**Review by MathisGD — APPROVED** [review]
LGTM 

Just one thing: tests pass when I replace the < by <= (so when the left child is the first account of the non-heap). Maybe it is worth adding a test for this ?

**Comment by QGarchery** [comment]
> LGTM
> 
> Just one thing: tests pass when I replace the < by <= (so when the left child is the first account of the non-heap). Maybe it is worth adding a test for this ?

Hmm not sure how to test that since it has the correct behavior, it is just less efficient

**Comment by MathisGD** [comment]
With <=, isn't there a case we are not shifting down but we don't need to ?

**Review by MerlinEgalite — APPROVED** [review]
LGTM

**Comment by QGarchery** [comment]
> With <=, isn't there a case we are not shifting down but we don't need to ?

We shift down more with the `<=` but that's not an issue because shifting would stop immediatly

**Pull request merged**
