### PR TITLE
Sync repo

### PR DESCRIPTION
**Pull request by QGarchery**

### CODE REVIEW

**Comment by MathisGD** [comment]
Sadly, we loose the reference to all the PRs that made all this work (merge commits point to PRs of this repo). Should we at least keep the private repo as a public archive for references ?

**Comment by MathisGD** [comment]
As I understood it, the strategy for synchronizing the two repo requires rolling back main at some point. I'm wondering if it would not be better to merge/rebase the changes of the private repo on public/main instead.

**Comment by QGarchery** [comment]
> As I understood it, the strategy for synchronizing the two repo requires rolling back main at some point. I'm wondering if it would not be better to merge/rebase the changes of the private repo on public/main instead.

I tried it and there is no conflict, but it does not mean that the added PRs are safe to rebase on. Doing so would prevent us to review the changes, because it would create one big PR with all the changes instead of 2 small PRs to review again

**Comment by MathisGD** [comment]
If you "merge" we don't need to review everything right ?

**Review by MerlinEgalite — DISMISSED** [review]

**Comment by QGarchery** [comment]
> If you "merge" we don't need to review everything right ?

I think you do, merging is not safe. I can easily create two branches that are both fine by themselves, but merging introduces a bug, even if there is no conflict between the two

**Comment by Tristan22400** [comment]
Is it okay to have unverified commit at the beginning of the PR ?

**Comment by MathisGD** [comment]
Yes it is ok @Tristan22400

**Review by Tristan22400 — DISMISSED** [review]

**Review by pakim249CAL — APPROVED** [review]

**Review by makcandrov — DISMISSED** [review]

**Pull request merged**
