### PR TITLE
Perf three heap (uncheckatoooooor)

### PR DESCRIPTION
**Pull request by MerlinEgalite**
This is just a suggestion. It might be possible to do the same on the "normal" heap.

### Reference
Screenshot 2022-10-29 at 10 31 26

### first commit
Screenshot 2022-10-29 at 14 44 43

### Second commit
Screenshot 2022-10-29 at 14 48 58

### Third commit
Screenshot 2022-10-29 at 14 50 10

### CODE REVIEW

**Comment by MathisGD** [comment]
nooo 😢

**Comment by MathisGD** [comment]
It is not my PR so I will let Quentin choose :-)

**Comment by QGarchery** [comment]
I think that if we want to optimize a lot the next step would be to write parts of the whole thing in Yul, so I'm closing this PR for now

**Comment by MerlinEgalite** [comment]
As you want

**Pull request closed without merging**
